// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/jeanSagaz/fc-clean-arch/internal/entity"
	"github.com/jeanSagaz/fc-clean-arch/internal/event"
	"github.com/jeanSagaz/fc-clean-arch/internal/infra/database"
	"github.com/jeanSagaz/fc-clean-arch/internal/usecase"
	"github.com/jeanSagaz/fc-clean-arch/pkg/events"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewUpdateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.UpdateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderUpdated := event.NewOrderUpdated()
	updateOrderUseCase := usecase.NewUpdateOrderUseCase(orderRepository, orderUpdated, eventDispatcher)
	return updateOrderUseCase
}

func NewDeleteOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.DeleteOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderDeleted := event.NewOrderDeleted()
	deleteOrderUseCase := usecase.NewDeleteOrderUseCase(orderRepository, orderDeleted, eventDispatcher)
	return deleteOrderUseCase
}

func NewListOrdersUseCase(db *sql.DB) *usecase.ListOrdersUseCase {
	orderRepository := database.NewOrderRepository(db)
	listOrdersUseCase := usecase.NewListOrdersUseCase(orderRepository)
	return listOrdersUseCase
}

func NewGetOrdesUseCase(db *sql.DB) *usecase.GetOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	getOrderUseCase := usecase.NewGetOrderUseCase(orderRepository)
	return getOrderUseCase
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))

var setOrderUpdatedEvent = wire.NewSet(event.NewOrderUpdated, wire.Bind(new(events.EventInterface), new(*event.OrderUpdated)))

var setOrderDeletedEvent = wire.NewSet(event.NewOrderDeleted, wire.Bind(new(events.EventInterface), new(*event.OrderDeleted)))
