CREATE TABLE orders (
  id varchar(36) NOT NULL,
  price DECIMAL(6,4) NOT NULL,
  tax DECIMAL(6,4) NOT NULL,
  final_price DECIMAL(6,4) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;